CREATE TABLE `user`(id INT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(20), PASSWORD VARCHAR(20),age INT);
INSERT INTO `user`(NAME,PASSWORD, age) VALUES('宋江','abc123', 24);
INSERT INTO `user`(NAME,PASSWORD, age) VALUES('晁盖','hhh456', 27);